EM-933 Throttling errors in send-message state machine
NHSDigital/terraform-aws-mesh-client pull request #156
Opened 2024-09-09 15:06 UTC by johnmarston-nhs

2024-09-09 15:08 UTC, johnmarston-nhs commented on scripts/self-signed-ca/conf/client.conf
> -authorityKeyIdentifier = keyid, issuer
https://github.com/openssl/openssl/issues/22966

`authorityKeyIdentifier` is not relevant for CSRs and causes errors on newer (3.2) versions of OpenSSL.

2024-09-09 15:10 UTC, johnmarston-nhs commented on scripts/self-signed-ca/create-server-cert.sh
> -openssl req -newkey rsa:2048 -nodes -keyout "${cert_key}" -new -out "${cert_csr}" -config "${csr_conf}" -extensions v3_req -addext "${san}"
In OpenSSL 3.1+, `-addext` does not play nice with the `v3_req` extension as I think the both contain `subjectAltName` - this causes a duplicate attribute error. This is going to be fixed in OpenSSL 3.4, but that branch isn't going to be in any distro any time soon.

Details: https://github.com/openssl/openssl/issues/11169#issuecomment-2207013616

2024-09-11 13:57 UTC, johnmarston-nhs commented on src/shared/common.py
> +def strtobool(value, raise_exc=False):
IMO, it made more sense to break this simple function out into something we have control over, rather than relying on package imports. I ~~nicked~~ ~~borrowed~~ took inspiration from [this](https://github.com/symonsoft/str2bool)

2024-09-13 13:38 UTC, johnwilliams57-nhs requested changes
looks good. just one question on the py version, which looks wrong.

2024-09-13 13:38 UTC, johnwilliams57-nhs commented on pyproject.toml
> +        3.11: py310
should this be py311?

2024-09-13 13:38 UTC, johnwilliams57-nhs commented on src/shared/common.py
> +def strtobool(value, raise_exc=False):
there's a _very_ similar function in mesh common. but that's in a private repo and this is public.
so fair enough.

2024-09-13 13:56 UTC, johnwilliams57-nhs approved these changes

2024-09-13 13:58 UTC, merged